server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Melayani file static Svelte SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Reverse proxy ke Backend API (di dalam jaringan Docker, nama container adalah hostnamenya)
    location /api/ {
        proxy_pass http://mixa-backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
